### ISSUE TITLE
Bug when user opens menu on mobile

### ISSUE THREAD

**Issue by AleksandraKozubal** [blumilksoftware/lmt#37]
When user opens menu, date moves onto counter.
![image](https://github.com/blumilksoftware/lmt/assets/104600942/8789bf5f-143e-4212-b930-37ae86ba82da)

**Comment by kamilpiech97** [comment]
I am closing that issue beacause we have new layout:
![image](https://github.com/user-attachments/assets/67eb7e02-c44d-459b-96d6-3f5c6fa7d5a0)
